name: 'Azure Kubernetes set context'
description: 'Sets the kubeconfig on the machine to communicate with the Azure Kubernetes cluster'
inputs: 
  creds:
    description: 'Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`'
    required: false
    default: ''
  resource-group:
    description: 'Resource Group Name'
    required: false
    default: ''
  cluster-name:
    description: 'AKS Cluster Name'
    required: false
    default: ''
  aad-creds:
    description: 'Azure credentials of the account containing AAD cluster i.e. output of `az ad sp create-for-rbac --skip-assignment`'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
